'use client'
import {useEffect,useState} from 'react'
import {useParams} from 'next/navigation'
import ProtectedLayout from '@/components/ProtectedLayout'
import Topbar from '@/components/Topbar'
import {useData} from '@/components/DataProvider'
import {getSupabaseBrowser} from '@/lib/supabase'

function Detail(){
 const {id}=useParams<{id:string}>();const {students}=useData();const student=students.find(s=>s.id===id);const [logs,setLogs]=useState<any[]>([]),[files,setFiles]=useState<any[]>([]),[msg,setMsg]=useState('');const supabase=getSupabaseBrowser()
 async function load(){if(!supabase)return;const [{data:l},{data:f}]=await Promise.all([supabase.from('lesson_logs').select('*').eq('student_id',id).order('class_date',{ascending:false}),supabase.from('student_files').select('*').eq('student_id',id).order('created_at',{ascending:false})]);setLogs(l||[]);setFiles(f||[])}
 useEffect(()=>{load()},[id])
 async function addLog(fd:FormData){if(!supabase){setMsg('Lesson history requires Supabase configuration.');return}const {error}=await supabase.from('lesson_logs').insert({student_id:id,class_date:String(fd.get('class_date')),homework_assigned:String(fd.get('homework_assigned')||''),next_lesson:String(fd.get('next_lesson')||''),lesson_note:String(fd.get('lesson_note')||''),attendance_status:String(fd.get('attendance_status')||'completed')});setMsg(error?.message||'Lesson saved.');load()}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!supabase)return;const path=`${id}/${Date.now()}-${file.name}`;const up=await supabase.storage.from('student-files').upload(path,file);if(up.error){setMsg(up.error.message);return}const {error}=await supabase.from('student_files').insert({student_id:id,file_name:file.name,storage_path:path,mime_type:file.type});setMsg(error?.message||'File uploaded.');load()}
 if(!student)return <div className="empty">Student not found.</div>
 return <><Topbar title={student.name} subtitle={`${student.subject||'No subject'} · lesson history, homework and syllabus`}/><div className="grid grid-2"><div className="card"><h3 className="section-title">Add date-wise lesson record</h3><form action={addLog} className="list"><div className="field"><label>Date</label><input className="input" type="date" name="class_date" defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="field"><label>What I taught / lesson note</label><textarea className="textarea" rows={3} name="lesson_note"/></div><div className="field"><label>Homework / assigned</label><textarea className="textarea" rows={3} name="homework_assigned"/></div><div className="field"><label>Next lesson / what to teach</label><textarea className="textarea" rows={3} name="next_lesson"/></div><div className="field"><label>Attendance status</label><select className="select" name="attendance_status"><option value="completed">Completed</option><option value="absent">Student absent</option><option value="cancelled">Cancelled</option><option value="rescheduled">Rescheduled</option><option value="missed">Missed</option></select></div><button className="btn btn-primary">Save lesson</button></form></div><div className="card"><h3 className="section-title">Syllabus & files</h3><input className="input" type="file" accept=".pdf,.doc,.docx,image/*" onChange={upload}/><p className="sub">Multiple files supported through the Supabase Storage bucket <b>student-files</b>.</p><div className="list">{files.map(f=><div className="list-item" key={f.id}><b>{f.file_name}</b><span className="badge">{f.mime_type||'file'}</span></div>)}</div></div></div><div className="card" style={{marginTop:16}}><h3 className="section-title">Lesson history</h3><div className="list">{logs.map(l=><div className="list-item" key={l.id}><div><b>{l.class_date} · {l.attendance_status}</b><div className="sub">Taught: {l.lesson_note||'—'}</div><div className="sub">Homework: {l.homework_assigned||'—'}</div><div className="sub">Next: {l.next_lesson||'—'}</div></div></div>)}{!logs.length&&<div className="empty">No lesson history yet.</div>}</div></div>{msg&&<div className="card" style={{marginTop:16}}>{msg}</div>}</>
}
export default function Page(){return <ProtectedLayout><Detail/></ProtectedLayout>}
