'use client'
import React,{createContext,useContext,useEffect,useMemo,useState} from 'react'
import { getSupabaseBrowser } from '@/lib/supabase'
import { demoSchedules,demoStudents,demoTasks } from '@/lib/demo'
import type {Payment,Schedule,ScheduleException,Settings,Student,TaskItem} from '@/lib/types'

type Ctx={students:Student[];schedules:Schedule[];exceptions:ScheduleException[];tasks:TaskItem[];payments:Payment[];settings:Settings;reload:()=>Promise<void>;saveStudent:(x:Partial<Student>)=>Promise<void>;archiveStudent:(id:string)=>Promise<void>;saveSchedule:(x:Partial<Schedule>&{student_id:string})=>Promise<void>;deleteSchedule:(id:string)=>Promise<void>;saveException:(x:Partial<ScheduleException>&{student_id:string;class_date:string;start_time:string;duration_minutes:number;status:ScheduleException['status']})=>Promise<void>;saveTask:(x:Partial<TaskItem>&{title:string})=>Promise<void>;savePayment:(x:Partial<Payment>&{student_id:string;month_key:string;amount:number})=>Promise<void>;saveSettings:(x:Partial<Settings>)=>Promise<void>}
const defaults:Settings={id:'default',day_start:'07:00',day_end:'22:00',interval_minutes:30,default_duration_minutes:60,reminder_minutes:30}
const C=createContext<Ctx|null>(null)
const LS='tutorgrid_demo_v1'

function uid(){return crypto.randomUUID()}
export function DataProvider({children}:{children:React.ReactNode}){
 const [students,setStudents]=useState<Student[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[exceptions,setExceptions]=useState<ScheduleException[]>([]),[tasks,setTasks]=useState<TaskItem[]>([]),[payments,setPayments]=useState<Payment[]>([]),[settings,setSettings]=useState<Settings>(defaults)
 const supabase=getSupabaseBrowser()
 function loadLocal(){const raw=localStorage.getItem(LS); if(raw){const d=JSON.parse(raw);setStudents(d.students||[]);setSchedules(d.schedules||[]);setExceptions(d.exceptions||[]);setTasks(d.tasks||[]);setPayments(d.payments||[]);setSettings(d.settings||defaults)}else{setStudents(demoStudents);setSchedules(demoSchedules);setTasks(demoTasks);persist({students:demoStudents,schedules:demoSchedules,exceptions:[],tasks:demoTasks,payments:[],settings:defaults})}}
 function persist(o:any){localStorage.setItem(LS,JSON.stringify(o))}
 function localSnapshot(overrides:any={}){return{students,schedules,exceptions,tasks,payments,settings,...overrides}}
 async function reload(){if(!supabase){loadLocal();return} const [a,b,c,d,e,f]=await Promise.all([supabase.from('students').select('*').order('name'),supabase.from('schedules').select('*,student:students(*)').eq('active',true),supabase.from('schedule_exceptions').select('*,student:students(*)'),supabase.from('tasks').select('*').order('due_at',{ascending:true}),supabase.from('payments').select('*,student:students(*)').order('paid_at',{ascending:false}),supabase.from('app_settings').select('*').limit(1).maybeSingle()]); if(a.error){loadLocal();return} setStudents(a.data||[]);setSchedules((b.data||[]) as any);setExceptions((c.data||[]) as any);setTasks((d.data||[]) as any);setPayments((e.data||[]) as any);if(f.data)setSettings(f.data as any)}
 useEffect(()=>{reload()},[])
 async function saveStudent(x:Partial<Student>){if(supabase){const row={name:x.name,subject:x.subject||'',color:x.color||'#4f46e5',phone:x.phone||null,notes:x.notes||null,monthly_fee:x.monthly_fee||0,archived:x.archived||false}; if(x.id) await supabase.from('students').update(row).eq('id',x.id); else await supabase.from('students').insert(row); await reload()}else{const next=x.id?students.map(s=>s.id===x.id?{...s,...x}:s):[...students,{id:uid(),name:x.name||'Student',subject:x.subject||'',color:x.color||'#4f46e5',archived:false,monthly_fee:x.monthly_fee||0,notes:x.notes||''}];setStudents(next);persist(localSnapshot({students:next}))}}
 async function archiveStudent(id:string){if(supabase){await supabase.from('students').update({archived:true}).eq('id',id);await reload()}else{const next=students.map(s=>s.id===id?{...s,archived:true}:s);setStudents(next);persist(localSnapshot({students:next}))}}
 async function saveSchedule(x:Partial<Schedule>&{student_id:string}){const row={student_id:x.student_id,day_of_week:x.day_of_week??0,start_time:x.start_time||'07:00',duration_minutes:x.duration_minutes||settings.default_duration_minutes,recurrence:'weekly' as const,active:x.active??true};if(supabase){if(x.id)await supabase.from('schedules').update(row).eq('id',x.id);else await supabase.from('schedules').insert(row);await reload()}else{const student=students.find(s=>s.id===x.student_id);const next=x.id?schedules.map(s=>s.id===x.id?{...s,...row,student} as Schedule:s):[...schedules,{id:uid(),...row,student} as Schedule];setSchedules(next);persist(localSnapshot({schedules:next}))}}
 async function deleteSchedule(id:string){if(supabase){await supabase.from('schedules').update({active:false}).eq('id',id);await reload()}else{const next=schedules.filter(s=>s.id!==id);setSchedules(next);persist(localSnapshot({schedules:next}))}}
 async function saveException(x:Partial<ScheduleException>&{student_id:string;class_date:string;start_time:string;duration_minutes:number;status:ScheduleException['status']}){if(supabase){await supabase.from('schedule_exceptions').upsert({schedule_id:x.schedule_id||null,student_id:x.student_id,class_date:x.class_date,start_time:x.start_time,duration_minutes:x.duration_minutes,status:x.status,original_date:x.original_date||null,note:x.note||null},{onConflict:'student_id,class_date,start_time'});await reload()}else{const ex={id:x.id||uid(),...x} as ScheduleException;const next=[...exceptions.filter(e=>!(e.student_id===x.student_id&&e.class_date===x.class_date&&e.start_time===x.start_time)),ex];setExceptions(next);persist(localSnapshot({exceptions:next}))}}
 async function saveTask(x:Partial<TaskItem>&{title:string}){const row={title:x.title,student_id:x.student_id||null,class_date:x.class_date||null,due_at:x.due_at||null,priority:x.priority||'medium',status:x.status||'todo',note:x.note||null};if(supabase){if(x.id)await supabase.from('tasks').update(row).eq('id',x.id);else await supabase.from('tasks').insert(row);await reload()}else{const next=x.id?tasks.map(t=>t.id===x.id?{...t,...row}:t):[...tasks,{id:uid(),...row} as TaskItem];setTasks(next);persist(localSnapshot({tasks:next}))}}
 async function savePayment(x:Partial<Payment>&{student_id:string;month_key:string;amount:number}){const row={student_id:x.student_id,month_key:x.month_key,amount:x.amount,note:x.note||null,paid_at:x.paid_at||new Date().toISOString()};if(supabase){await supabase.from('payments').insert(row);await reload()}else{const student=students.find(s=>s.id===x.student_id);const next=[{id:uid(),...row,student} as Payment,...payments];setPayments(next);persist(localSnapshot({payments:next}))}}
 async function saveSettings(x:Partial<Settings>){const row={...settings,...x};if(supabase){await supabase.from('app_settings').upsert(row);await reload()}else{setSettings(row);persist(localSnapshot({settings:row}))}}
 const value=useMemo(()=>({students,schedules,exceptions,tasks,payments,settings,reload,saveStudent,archiveStudent,saveSchedule,deleteSchedule,saveException,saveTask,savePayment,saveSettings}),[students,schedules,exceptions,tasks,payments,settings])
 return <C.Provider value={value}>{children}</C.Provider>
}
export function useData(){const x=useContext(C);if(!x)throw new Error('useData must be inside DataProvider');return x}
