'use client'
import {useState} from 'react'
import ProtectedLayout from '@/components/ProtectedLayout'
import Topbar from '@/components/Topbar'
import Modal from '@/components/Modal'
import {useData} from '@/components/DataProvider'
import {Plus,Search,Archive,FileText} from 'lucide-react'
import Link from 'next/link'

function Students(){
 const {students,saveStudent,archiveStudent}=useData(); const [q,setQ]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<any>(null)
 const shown=students.filter(s=>!s.archived&&(s.name+' '+s.subject).toLowerCase().includes(q.toLowerCase()))
 async function submit(fd:FormData){await saveStudent({id:editing?.id,name:String(fd.get('name')),subject:String(fd.get('subject')),monthly_fee:Number(fd.get('monthly_fee')||0),notes:String(fd.get('notes')||''),color:String(fd.get('color')||'#4f46e5')});setModal(false);setEditing(null)}
 return <><Topbar title="Students" subtitle="Profiles, lesson notes, syllabus and monthly fee" actions={<button className="btn btn-primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={16}/> Add student</button>}/><div className="toolbar"><div style={{position:'relative',maxWidth:320,width:'100%'}}><Search size={16} style={{position:'absolute',left:12,top:12,color:'#98a2b3'}}/><input className="input" style={{paddingLeft:36}} placeholder="Search student or subject" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="student-grid">{shown.map(s=><div className="student-card" key={s.id}><div className="student-head"><div className="avatar" style={{background:s.color}}>{s.name.slice(0,1).toUpperCase()}</div><div><b>{s.name}</b><div className="sub">{s.subject||'No subject set'}</div></div></div><div className="sub" style={{marginTop:12}}>{s.notes||'No notes yet.'}</div><div className="toolbar" style={{margin:'14px 0 0'}}><Link className="btn btn-soft" href={`/students/${s.id}`}>Open</Link><button className="btn btn-soft" onClick={()=>{setEditing(s);setModal(true)}}>Edit</button><button className="btn btn-ghost" onClick={()=>alert('Syllabus upload UI is ready for Supabase Storage. Configure the bucket named student-files to enable uploads.')}><FileText size={15}/> Syllabus</button><button className="btn btn-ghost" onClick={()=>archiveStudent(s.id)}><Archive size={15}/> Archive</button></div></div>)}</div>{modal&&<Modal title={editing?'Edit student':'Add student'} onClose={()=>setModal(false)}><form action={submit} className="form-grid"><div className="field"><label>Student name</label><input className="input" name="name" defaultValue={editing?.name||''} required/></div><div className="field"><label>Subject</label><input className="input" name="subject" defaultValue={editing?.subject||''}/></div><div className="field"><label>Monthly fee (BDT)</label><input className="input" name="monthly_fee" type="number" defaultValue={editing?.monthly_fee||0}/></div><div className="field"><label>Color</label><input className="input" name="color" type="color" defaultValue={editing?.color||'#4f46e5'}/></div><div className="field" style={{gridColumn:'1/-1'}}><label>Notes</label><textarea className="textarea" name="notes" rows={4} defaultValue={editing?.notes||''}/></div><div><button className="btn btn-primary" type="submit">Save student</button></div></form></Modal>}</>
}
export default function Page(){return <ProtectedLayout><Students/></ProtectedLayout>}
